[gspread]
type = "service_account"
project_id = "wahabmedical"
private_key_id = "fa2b08ff882ce37f736ea1262220dee3edcb3955"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHg02okM4sM/AR
UtF+8UWy+WE33t4uSdtaWxxJn2/oglPhIyqCas8vx/zKeVcn2dSBjmfj7T3mYZzK
CkzX+V/aZ68OW36Hu10n7pxPDOfwE87pKPk3txv/GZwx5JsSSUvht1ZVj0XEFzze
ef1DLypbRiyeBLhmGksX+gywu1qhygy8rBNNl8VexTy+Kfww5NkH6qBen0NpgJB3
GYsjhRA22l+lPjmkKMOYiZlpU5Afoy1WLf9TiLD18rYcF8D3Pb8AqDjSTJYj0GcW
BsX4vfBr/iYPbH9r/HX747zFtCK78HdMov+5Hg0Ho0zfP9oNSA/Z+2+TNkDnZ/0c
VmRmbxZXAgMBAAECggEAID5UrSLl5xfnuuz/BXx5rrCF6TEgCCwQgrxJyI43WETD
yJVV1+jqHgc8j/5nOv4FzYBVwuzC/boVzEM44wie2J28GV5pBwedSQhTg6UK0O5q
mJzyFfKGWEZry1ZuR1jIJizqi35RoJy+zhe5+gMj3cdsC4eow3uJWlEjfuZwgcfs
DJvultzFEu9NUOKpy5VHuND/nJzxRQ3R6kPjrxhvMNOMK7dAGrYytly/q6OuPCEp
0IPS56y3BskJXFSmNUWQTqCV8L2qOucj9d24zaUbgzzly5fhhR14OJOVz/Wdylpi
8GAv19gWX6RcCV/UG8BFwZWm3GV2VtDGEvlniZ6zYQKBgQDpGT17KjFK13rfb6P0
F1hGxg3ZhDyCneYCS3hdToFo17NYflRZvGvU16N7hA+RVsK2YJCJ855rY8Af3ZzF
wHisYkHK2nA3b1e81TJeNnn6bpC+rBpj55RaueBqZzKQKwgmgdukhOUOH4CvJ0n+
W1n3elTVUqiAbBMs8qq75C+H4QKBgQDbHVXjLhZFXGQi1Y00sz8S6eCJeEbvltNe
Ur3uTP4vM96mZE7f6xDzVRN1ovU6KeYiTG55K2DGJSbTEmfTTG6Tyt0wVounYiyt
Rj1M6KmFUt8i8y2huRklXz1VTgYRdgODIe8TLPklAXjgK1QfdGIZuwp/9CS8+4D5
mMgz/sGFNwKBgQDFbnhxmqIXhv1uxKt0slU11MikROnPpBfON8giF71qZNBmEtI1
E2+t3lt84bUh3/+Z455pCexTfzCajOUdZdGQCMU7INtNSMRij51SyQd1wzJcHX9Y
wSwZ0DgxR2k/TQNhQjocVeeAl9QyBrAYfZ1tDLNP3+wSofd36a4M6NANYQKBgGZG
FRbLJj4N1/eichyNJf2wCMxhxcqDPfmi6WBXs7VYoq5L170QvYK2zTR1cb1KXU7Z
Gh+Yrb0PDkYrKycnX93ALOopG1pvqqbeSDKjzqyad+iaVUxNV31oLPqqRo7T5OPK
bQsoTMqHG2KXFtbvvfKAqW/8B0HmqtbWB2ytlqqVAoGBAOfB0tplWe5FiabWX7a0
pv5DUqIZXSIkAThGtLcwdXOVBA9chUVqJwIr9UXkGh+cayU406FINl7e4La+tvpt
RrzRcKO4Qw3f0YRkYY06ml+Hqr0lYdijuaWu/Lk414qp3MgfonmIZPdjABr7fmDG
Nq69iKhdibYSHK7jSDS5RSwr
-----END PRIVATE KEY-----
"""
client_email = "wahab1-drug-house@wahabmedical.iam.gserviceaccount.com"
client_id = "113807677150765285544"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/wahab1-drug-house%40wahabmedical.iam.gserviceaccount.com"
